//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblReports = new HashSet<tblReport>();
            this.tblProjects = new HashSet<tblProject>();
        }
    
        public int EmployeeID { get; set; }
        public int YearsOfService { get; set; }
        public string Salary { get; set; }
        public string EducationDegree { get; set; }
        public int UserID { get; set; }
        public int ManagerID { get; set; }
        public int SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
    
        public virtual tblManager tblManager { get; set; }
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReport> tblReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProject> tblProjects { get; set; }
    }
}
