//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_I_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportID { get; set; }
        public string ProjectClientName { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string WorkDescription { get; set; }
        public int TotalHours { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
